name: Build Java JAR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Download your code from GitHub
        uses: actions/checkout@v3

      - name: 2. Install Java 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: 3. Build the JAR using Maven
        run: mvn clean package -DskipTests

      - name: 4. Run Snyk Security Scan
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=high

      - name: 5. Upload Snyk results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        continue-on-error: true
        with:
          sarif_file: snyk.sarif

      - name: 6. Upload the JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/*.jar